# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b607dcd6876888612a2d5f616430b5c916d63b43b2913ffb5e6a9b1a380c22f35cd47f038731b9a3e01dcff7d36ec133220dd7e88c6a9fe7aa08b1aacef28e9a

test:
  secret_key_base: 753579f252fc588e7637c7f9a1c388941277a06217171f42fdccc60606af4664cc41938932aeedfee7544ab388f38f810682f8421746920855a9a018146c3cca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
