# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df2845e933db930bc02fb21cc740b02536ecb8a1bfc74c0999142a875b7e1a07ec3a4c2ec4b4633ab0df2f6bb0d5fc20ae3809c40daa0e3d2b5f71e0308b82b9

test:
  secret_key_base: d5cc4190b942638eb8533ed4ede1dfa381cb22821f4f7937b8dc280c66c99685a18b88042b0570550e0d51039635671843ba8de7da98af093cec1581613d6fca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
